### ISSUE TITLE
hidden custom js inclusion to external site.

### ISSUE THREAD

**Issue by danmarsden** [jsxgraph/moodle-jsxgraph-plugin#9]
You are hosting some JS on your site that can be unexpectedly included in the users site.
http://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore-0.99.5.js

You should remove this or make it very clear in the readme/description of your plugin.

**Comment by walterandreas** [comment]
As explained in my comment on issue #10, the inclusion of external code is essential, as it is necessary to fulfill a user's request. In our README file this possibility of integration from an external site is already explained (see https://github.com/jsxgraph/moodle-filter_jsxgraph#admin-settings). In addition, it is made clear in the administration of the filter that an external server is requested with the appropriate settings. 
![screenshot](https://user-images.githubusercontent.com/30598361/50386639-48cd3500-06eb-11e9-8a2a-683ca9f1cea9.png)

Since version 0.99.5 is only available on our server (http://jsxgraph.uni-bayreuth.de) the link can not be removed.

If necessary, further information can be entered in our README file.
